/* this file has been generated by gModbus on Tue Oct 20 12:14:04 2015 */

#ifndef _THREAD_SAFE
#define _THREAD_SAFE
#endif
#include "msxe371x_modbus_clientlib.h"

int modbus_call_MX371x__getNumberOfChannels(struct modbus * modbus,struct MX371x__getNumberOfChannels_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 100, Response, sizeof( struct MX371x__getNumberOfChannels_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ChannelNumber = MODBUS_HTONL(Response->ChannelNumber);

	}

	return 0;
}
int modbus_call_MX371x__getNumberOfChannelsEx(struct modbus * modbus,struct MX371x__getNumberOfChannelsEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1000, Response, sizeof( struct MX371x__getNumberOfChannelsEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ChannelNumber = MODBUS_HTONL(Response->ChannelNumber);

	}

	return 0;
}
int modbus_call_MX371x__TransducerGetAutoRefreshValues(struct modbus * modbus,struct MX371x__TransducerGetAutoRefreshValues_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 101, Response, sizeof( struct MX371x__TransducerGetAutoRefreshValues_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		{
			int i;
			for(i=0;i<17;i++)
			{
				Response->Value[i] = MODBUS_HTONL(Response->Value[i]);
			}
		}
	}

	return 0;
}
int modbus_call_MX371x__TransducerGetAutoRefreshValuesEx(struct modbus * modbus,struct MX371x__TransducerGetAutoRefreshValuesEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1050, Response, sizeof( struct MX371x__TransducerGetAutoRefreshValuesEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		{
			int i;
			for(i=0;i<17;i++)
			{
				Response->Value[i] = MODBUS_HTONL(Response->Value[i]);
			}
		}
	}

	return 0;
}
int modbus_call_MSXE371x__ExternalTemperatureRead(struct modbus * modbus,struct MSXE371x__ExternalTemperatureRead_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 102, Response, sizeof( struct MSXE371x__ExternalTemperatureRead_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->Value = MODBUS_HTONL(Response->Value);

		Response->TimeStampLow = MODBUS_HTONL(Response->TimeStampLow);

		Response->TimeStampHigh = MODBUS_HTONL(Response->TimeStampHigh);

	}

	return 0;
}
int modbus_call_MSXE371x__ExternalTemperatureReadEx(struct modbus * modbus,struct MSXE371x__ExternalTemperatureReadEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1200, Response, sizeof( struct MSXE371x__ExternalTemperatureReadEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->Value = MODBUS_HTONL(Response->Value);

		Response->TimeStampLow = MODBUS_HTONL(Response->TimeStampLow);

		Response->TimeStampHigh = MODBUS_HTONL(Response->TimeStampHigh);

	}

	return 0;
}
int modbus_call_MX371x__TransducerGetNbrOfType(struct modbus * modbus,struct MX371x__TransducerGetNbrOfType_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 103, Response, sizeof( struct MX371x__TransducerGetNbrOfType_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->NumberOfTransducerTypes = MODBUS_HTONL(Response->NumberOfTransducerTypes);

	}

	return 0;
}
int modbus_call_MX371x__TransducerGetNbrOfTypeEx(struct modbus * modbus,struct MX371x__TransducerGetNbrOfTypeEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1212, Response, sizeof( struct MX371x__TransducerGetNbrOfTypeEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->NumberOfTransducerTypes = MODBUS_HTONL(Response->NumberOfTransducerTypes);

	}

	return 0;
}
int modbus_call_MX371x__GetTransducerDatabaseCursor(struct modbus * modbus,struct MX371x__GetTransducerDatabaseCursor_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 104, Response, sizeof( struct MX371x__GetTransducerDatabaseCursor_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->TransducerDatabaseCursor = MODBUS_HTONL(Response->TransducerDatabaseCursor);

	}

	return 0;
}
int modbus_call_MX371x__GetTransducerDatabaseCursorEx(struct modbus * modbus,struct MX371x__GetTransducerDatabaseCursorEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1216, Response, sizeof( struct MX371x__GetTransducerDatabaseCursorEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->TransducerDatabaseCursor = MODBUS_HTONL(Response->TransducerDatabaseCursor);

	}

	return 0;
}
int modbus_call_MX371x__TransducerGetTypeInformation(struct modbus * modbus,struct MX371x__TransducerGetTypeInformation_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 105, Response, sizeof( struct MX371x__TransducerGetTypeInformation_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->SelectionIndex = MODBUS_HTONL(Response->SelectionIndex);

		Response->CalibratedChannels = MODBUS_HTONL(Response->CalibratedChannels);

		Response->Type = MODBUS_HTONL(Response->Type);

		Response->Frequency = MODBUS_HTONL(Response->Frequency);

		Response->Impedance = MODBUS_HTONL(Response->Impedance);

		Response->NominalVoltage = MODBUS_HTONF(Response->NominalVoltage);

		Response->Sensibility = MODBUS_HTONF(Response->Sensibility);

		Response->Range = MODBUS_HTONF(Response->Range);

	}

	return 0;
}
int modbus_call_MX371x__TransducerGetTypeInformationEx(struct modbus * modbus,struct MX371x__TransducerGetTypeInformationEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1220, Response, sizeof( struct MX371x__TransducerGetTypeInformationEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->SelectionIndex = MODBUS_HTONL(Response->SelectionIndex);

		Response->CalibratedChannels = MODBUS_HTONL(Response->CalibratedChannels);

		Response->Type = MODBUS_HTONL(Response->Type);

		Response->Frequency = MODBUS_HTONL(Response->Frequency);

		Response->Impedance = MODBUS_HTONL(Response->Impedance);

		Response->NominalVoltage = MODBUS_HTONF(Response->NominalVoltage);

		Response->Sensibility = MODBUS_HTONF(Response->Sensibility);

		Response->Range = MODBUS_HTONF(Response->Range);

	}

	return 0;
}
int modbus_call_MX371x__TransducerInitPrimaryConnectionTest(struct modbus * modbus,struct MX371x__TransducerInitPrimaryConnectionTest_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 106, Response, sizeof( struct MX371x__TransducerInitPrimaryConnectionTest_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->TransducerInitPrimaryConnection = MODBUS_HTONL(Response->TransducerInitPrimaryConnection);

	}

	return 0;
}
int modbus_call_MX371x__TransducerInitPrimaryConnectionTestEx(struct modbus * modbus,struct MX371x__TransducerInitPrimaryConnectionTestEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1218, Response, sizeof( struct MX371x__TransducerInitPrimaryConnectionTestEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->TransducerInitPrimaryConnection = MODBUS_HTONL(Response->TransducerInitPrimaryConnection);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestPrimaryConnection(struct modbus * modbus,struct MX371x__TransducerTestPrimaryConnection_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 107, Response, sizeof( struct MX371x__TransducerTestPrimaryConnection_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestPrimaryConnectionEx(struct modbus * modbus,struct MX371x__TransducerTestPrimaryConnectionEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1222, Response, sizeof( struct MX371x__TransducerTestPrimaryConnectionEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestPrimaryShortCircuit(struct modbus * modbus,struct MX371x__TransducerTestPrimaryShortCircuit_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 108, Response, sizeof( struct MX371x__TransducerTestPrimaryShortCircuit_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulStatus = MODBUS_HTONL(Response->ulStatus);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestPrimaryShortCircuitEx(struct modbus * modbus,struct MX371x__TransducerTestPrimaryShortCircuitEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1224, Response, sizeof( struct MX371x__TransducerTestPrimaryShortCircuitEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulStatus = MODBUS_HTONL(Response->ulStatus);

	}

	return 0;
}
int modbus_call_MX371x__TransducerRearmPrimary(struct modbus * modbus,struct MX371x__TransducerRearmPrimary_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 109, Response, sizeof( struct MX371x__TransducerRearmPrimary_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerRearmPrimaryEx(struct modbus * modbus,struct MX371x__TransducerRearmPrimaryEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1226, Response, sizeof( struct MX371x__TransducerRearmPrimaryEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection0(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection0_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 110, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection0_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection0Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection0Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1228, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection0Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection1(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection1_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 111, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection1_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection1Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection1Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1230, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection1Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection2(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection2_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 112, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection2_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection2Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection2Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1232, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection2Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection3(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection3_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 113, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection3_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection3Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection3Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1234, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection3Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection4(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection4_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 114, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection4_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection4Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection4Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1236, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection4Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection5(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection5_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 115, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection5_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection5Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection5Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1238, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection5Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection6(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection6_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 116, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection6_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection6Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection6Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1240, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection6Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection7(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection7_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 117, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection7_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryConnection7Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryConnection7Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1242, Response, sizeof( struct MX371x__TransducerTestSecondaryConnection7Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit0(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit0_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 118, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit0_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit0Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit0Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1244, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit0Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit1(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit1_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 119, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit1_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit1Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit1Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1246, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit1Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit2(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit2_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 120, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit2_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit2Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit2Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1248, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit2Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit3(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit3_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 121, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit3_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit3Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit3Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1250, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit3Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit4(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit4_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 122, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit4_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit4Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit4Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1252, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit4Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit5(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit5_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 123, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit5_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit5Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit5Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1254, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit5Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit6(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit6_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 124, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit6_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit6Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit6Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1256, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit6Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit7(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit7_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 125, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit7_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MX371x__TransducerTestSecondaryShortCircuit7Ex(struct modbus * modbus,struct MX371x__TransducerTestSecondaryShortCircuit7Ex_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1258, Response, sizeof( struct MX371x__TransducerTestSecondaryShortCircuit7Ex_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

	}

	return 0;
}
int modbus_call_MSXE371x__InternalTemperatureRead(struct modbus * modbus,struct MSXE371x__InternalTemperatureRead_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 126, Response, sizeof( struct MSXE371x__InternalTemperatureRead_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->fInternalTemperature = MODBUS_HTONF(Response->fInternalTemperature);

	}

	return 0;
}
int modbus_call_MSXE371x__InternalTemperatureReadEx(struct modbus * modbus,struct MSXE371x__InternalTemperatureReadEx_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1260, Response, sizeof( struct MSXE371x__InternalTemperatureReadEx_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->fInternalTemperature = MODBUS_HTONF(Response->fInternalTemperature);

	}

	return 0;
}
int modbus_call_MSXE371x__IncCounterRead32BitValue(struct modbus * modbus,struct MSXE371x__IncCounterRead32BitValue_parameters_t * Response)
{
	int ret = 0;

	ret = modbus_send_FC3_query(modbus, 0, 1600, Response, sizeof( struct MSXE371x__IncCounterRead32BitValue_parameters_t) );

	/* return 0 on success, -1 on system error, -2 on MODBUS exception (the exception code is in modbus->exception), -3 if response from remote system is incorrect */
	/* error ? */
	if(ret) return ret;

	/* convert data from network to host format */
	{
		Response->ulValue = MODBUS_HTONL(Response->ulValue);

		Response->ulTimeStampLow = MODBUS_HTONL(Response->ulTimeStampLow);

		Response->ulTimeStampHigh = MODBUS_HTONL(Response->ulTimeStampHigh);

	}

	return 0;
}
int modbus_call_MX371x__TransducerInitAndStartAutoRefresh(struct modbus * modbus,
	uint32_t TransducerSelection,
	uint32_t ChannelMask,
	uint32_t AverageMode,
	uint32_t AverageValue,
	uint32_t TriggerMask,
	uint32_t TriggerMode,
	uint32_t HardwareTriggerEdge,
	uint32_t HardwareTriggerCount,
	uint32_t ByTriggerNbrOfSeqToAcquire,
	uint32_t DataFormat,
	uint32_t Option1,
	uint32_t Option2,
	uint32_t Option3,
	uint32_t Option4,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MX371x__TransducerInitAndStartAutoRefresh_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.TransducerSelection = MODBUS_NTOHL(TransducerSelection);
	MODBUS_DBG("TransducerSelection=%u\n",(uint32_t)MODBUS_NTOHL(params.TransducerSelection));
	params.ChannelMask = MODBUS_NTOHL(ChannelMask);
	MODBUS_DBG("ChannelMask=%u\n",(uint32_t)MODBUS_NTOHL(params.ChannelMask));
	params.AverageMode = MODBUS_NTOHL(AverageMode);
	MODBUS_DBG("AverageMode=%u\n",(uint32_t)MODBUS_NTOHL(params.AverageMode));
	params.AverageValue = MODBUS_NTOHL(AverageValue);
	MODBUS_DBG("AverageValue=%u\n",(uint32_t)MODBUS_NTOHL(params.AverageValue));
	params.TriggerMask = MODBUS_NTOHL(TriggerMask);
	MODBUS_DBG("TriggerMask=%u\n",(uint32_t)MODBUS_NTOHL(params.TriggerMask));
	params.TriggerMode = MODBUS_NTOHL(TriggerMode);
	MODBUS_DBG("TriggerMode=%u\n",(uint32_t)MODBUS_NTOHL(params.TriggerMode));
	params.HardwareTriggerEdge = MODBUS_NTOHL(HardwareTriggerEdge);
	MODBUS_DBG("HardwareTriggerEdge=%u\n",(uint32_t)MODBUS_NTOHL(params.HardwareTriggerEdge));
	params.HardwareTriggerCount = MODBUS_NTOHL(HardwareTriggerCount);
	MODBUS_DBG("HardwareTriggerCount=%u\n",(uint32_t)MODBUS_NTOHL(params.HardwareTriggerCount));
	params.ByTriggerNbrOfSeqToAcquire = MODBUS_NTOHL(ByTriggerNbrOfSeqToAcquire);
	MODBUS_DBG("ByTriggerNbrOfSeqToAcquire=%u\n",(uint32_t)MODBUS_NTOHL(params.ByTriggerNbrOfSeqToAcquire));
	params.DataFormat = MODBUS_NTOHL(DataFormat);
	MODBUS_DBG("DataFormat=%u\n",(uint32_t)MODBUS_NTOHL(params.DataFormat));
	params.Option1 = MODBUS_NTOHL(Option1);
	MODBUS_DBG("Option1=%u\n",(uint32_t)MODBUS_NTOHL(params.Option1));
	params.Option2 = MODBUS_NTOHL(Option2);
	MODBUS_DBG("Option2=%u\n",(uint32_t)MODBUS_NTOHL(params.Option2));
	params.Option3 = MODBUS_NTOHL(Option3);
	MODBUS_DBG("Option3=%u\n",(uint32_t)MODBUS_NTOHL(params.Option3));
	params.Option4 = MODBUS_NTOHL(Option4);
	MODBUS_DBG("Option4=%u\n",(uint32_t)MODBUS_NTOHL(params.Option4));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MX371x__TransducerInitAndStartAutoRefreshEx(struct modbus * modbus,
	uint32_t TransducerSelection,
	uint32_t ChannelMask,
	uint32_t AverageMode,
	uint32_t AverageValue,
	uint32_t TriggerMask,
	uint32_t TriggerMode,
	uint32_t HardwareTriggerEdge,
	uint32_t HardwareTriggerCount,
	uint32_t ByTriggerNbrOfSeqToAcquire,
	uint32_t DataFormat,
	uint32_t Option1,
	uint32_t Option2,
	uint32_t Option3,
	uint32_t Option4,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MX371x__TransducerInitAndStartAutoRefreshEx_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.TransducerSelection = MODBUS_NTOHL(TransducerSelection);
	MODBUS_DBG("TransducerSelection=%u\n",(uint32_t)MODBUS_NTOHL(params.TransducerSelection));
	params.ChannelMask = MODBUS_NTOHL(ChannelMask);
	MODBUS_DBG("ChannelMask=%u\n",(uint32_t)MODBUS_NTOHL(params.ChannelMask));
	params.AverageMode = MODBUS_NTOHL(AverageMode);
	MODBUS_DBG("AverageMode=%u\n",(uint32_t)MODBUS_NTOHL(params.AverageMode));
	params.AverageValue = MODBUS_NTOHL(AverageValue);
	MODBUS_DBG("AverageValue=%u\n",(uint32_t)MODBUS_NTOHL(params.AverageValue));
	params.TriggerMask = MODBUS_NTOHL(TriggerMask);
	MODBUS_DBG("TriggerMask=%u\n",(uint32_t)MODBUS_NTOHL(params.TriggerMask));
	params.TriggerMode = MODBUS_NTOHL(TriggerMode);
	MODBUS_DBG("TriggerMode=%u\n",(uint32_t)MODBUS_NTOHL(params.TriggerMode));
	params.HardwareTriggerEdge = MODBUS_NTOHL(HardwareTriggerEdge);
	MODBUS_DBG("HardwareTriggerEdge=%u\n",(uint32_t)MODBUS_NTOHL(params.HardwareTriggerEdge));
	params.HardwareTriggerCount = MODBUS_NTOHL(HardwareTriggerCount);
	MODBUS_DBG("HardwareTriggerCount=%u\n",(uint32_t)MODBUS_NTOHL(params.HardwareTriggerCount));
	params.ByTriggerNbrOfSeqToAcquire = MODBUS_NTOHL(ByTriggerNbrOfSeqToAcquire);
	MODBUS_DBG("ByTriggerNbrOfSeqToAcquire=%u\n",(uint32_t)MODBUS_NTOHL(params.ByTriggerNbrOfSeqToAcquire));
	params.DataFormat = MODBUS_NTOHL(DataFormat);
	MODBUS_DBG("DataFormat=%u\n",(uint32_t)MODBUS_NTOHL(params.DataFormat));
	params.Option1 = MODBUS_NTOHL(Option1);
	MODBUS_DBG("Option1=%u\n",(uint32_t)MODBUS_NTOHL(params.Option1));
	params.Option2 = MODBUS_NTOHL(Option2);
	MODBUS_DBG("Option2=%u\n",(uint32_t)MODBUS_NTOHL(params.Option2));
	params.Option3 = MODBUS_NTOHL(Option3);
	MODBUS_DBG("Option3=%u\n",(uint32_t)MODBUS_NTOHL(params.Option3));
	params.Option4 = MODBUS_NTOHL(Option4);
	MODBUS_DBG("Option4=%u\n",(uint32_t)MODBUS_NTOHL(params.Option4));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1250,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MX371x__TransducerStopAndReleaseAutoRefresh(struct modbus * modbus,
	uint32_t Dummy,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MX371x__TransducerStopAndReleaseAutoRefresh_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.Dummy = MODBUS_NTOHL(Dummy);
	MODBUS_DBG("Dummy=%u\n",(uint32_t)MODBUS_NTOHL(params.Dummy));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 2,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MX371x__TransducerStopAndReleaseAutoRefreshEx(struct modbus * modbus,
	uint32_t Dummy,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MX371x__TransducerStopAndReleaseAutoRefreshEx_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.Dummy = MODBUS_NTOHL(Dummy);
	MODBUS_DBG("Dummy=%u\n",(uint32_t)MODBUS_NTOHL(params.Dummy));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1300,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MX371x__TransducerInitAndStartSequence(struct modbus * modbus,
	uint32_t TransducerSelection,
	uint32_t NbrOfChannel,
	uint32_t ChannelList[8],
	uint32_t NbrOfSequence,
	uint32_t NbrMaxSequenceToTransfer,
	uint32_t DelayMode,
	uint32_t DelayTimeUnit,
	uint32_t DelayValue,
	uint32_t TriggerMask,
	uint32_t TriggerMode,
	uint32_t HardwareTriggerEdge,
	uint32_t HardwareTriggerCount,
	uint32_t ByTriggerNbrOfSeqToAcquire,
	uint32_t DataFormat,
	uint32_t Option1,
	uint32_t Option2,
	uint32_t Option3,
	uint32_t Option4,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MX371x__TransducerInitAndStartSequence_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.TransducerSelection = MODBUS_NTOHL(TransducerSelection);
	MODBUS_DBG("TransducerSelection=%u\n",(uint32_t)MODBUS_NTOHL(params.TransducerSelection));
	params.NbrOfChannel = MODBUS_NTOHL(NbrOfChannel);
	MODBUS_DBG("NbrOfChannel=%u\n",(uint32_t)MODBUS_NTOHL(params.NbrOfChannel));
	{
		int i;
		for(i=0;i<8;i++)
		{
			params.ChannelList[i] = MODBUS_NTOHL(ChannelList[i]);
			MODBUS_DBG("ChannelList=%u\n",(uint32_t)MODBUS_NTOHL(params.ChannelList[i]));
		}
	}
	params.NbrOfSequence = MODBUS_NTOHL(NbrOfSequence);
	MODBUS_DBG("NbrOfSequence=%u\n",(uint32_t)MODBUS_NTOHL(params.NbrOfSequence));
	params.NbrMaxSequenceToTransfer = MODBUS_NTOHL(NbrMaxSequenceToTransfer);
	MODBUS_DBG("NbrMaxSequenceToTransfer=%u\n",(uint32_t)MODBUS_NTOHL(params.NbrMaxSequenceToTransfer));
	params.DelayMode = MODBUS_NTOHL(DelayMode);
	MODBUS_DBG("DelayMode=%u\n",(uint32_t)MODBUS_NTOHL(params.DelayMode));
	params.DelayTimeUnit = MODBUS_NTOHL(DelayTimeUnit);
	MODBUS_DBG("DelayTimeUnit=%u\n",(uint32_t)MODBUS_NTOHL(params.DelayTimeUnit));
	params.DelayValue = MODBUS_NTOHL(DelayValue);
	MODBUS_DBG("DelayValue=%u\n",(uint32_t)MODBUS_NTOHL(params.DelayValue));
	params.TriggerMask = MODBUS_NTOHL(TriggerMask);
	MODBUS_DBG("TriggerMask=%u\n",(uint32_t)MODBUS_NTOHL(params.TriggerMask));
	params.TriggerMode = MODBUS_NTOHL(TriggerMode);
	MODBUS_DBG("TriggerMode=%u\n",(uint32_t)MODBUS_NTOHL(params.TriggerMode));
	params.HardwareTriggerEdge = MODBUS_NTOHL(HardwareTriggerEdge);
	MODBUS_DBG("HardwareTriggerEdge=%u\n",(uint32_t)MODBUS_NTOHL(params.HardwareTriggerEdge));
	params.HardwareTriggerCount = MODBUS_NTOHL(HardwareTriggerCount);
	MODBUS_DBG("HardwareTriggerCount=%u\n",(uint32_t)MODBUS_NTOHL(params.HardwareTriggerCount));
	params.ByTriggerNbrOfSeqToAcquire = MODBUS_NTOHL(ByTriggerNbrOfSeqToAcquire);
	MODBUS_DBG("ByTriggerNbrOfSeqToAcquire=%u\n",(uint32_t)MODBUS_NTOHL(params.ByTriggerNbrOfSeqToAcquire));
	params.DataFormat = MODBUS_NTOHL(DataFormat);
	MODBUS_DBG("DataFormat=%u\n",(uint32_t)MODBUS_NTOHL(params.DataFormat));
	params.Option1 = MODBUS_NTOHL(Option1);
	MODBUS_DBG("Option1=%u\n",(uint32_t)MODBUS_NTOHL(params.Option1));
	params.Option2 = MODBUS_NTOHL(Option2);
	MODBUS_DBG("Option2=%u\n",(uint32_t)MODBUS_NTOHL(params.Option2));
	params.Option3 = MODBUS_NTOHL(Option3);
	MODBUS_DBG("Option3=%u\n",(uint32_t)MODBUS_NTOHL(params.Option3));
	params.Option4 = MODBUS_NTOHL(Option4);
	MODBUS_DBG("Option4=%u\n",(uint32_t)MODBUS_NTOHL(params.Option4));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 3,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MX371x__TransducerInitAndStartSequenceEx(struct modbus * modbus,
	uint32_t TransducerSelection,
	uint32_t NbrOfChannel,
	uint32_t ChannelList[8],
	uint32_t NbrOfSequence,
	uint32_t NbrMaxSequenceToTransfer,
	uint32_t DelayMode,
	uint32_t DelayTimeUnit,
	uint32_t DelayValue,
	uint32_t TriggerMask,
	uint32_t TriggerMode,
	uint32_t HardwareTriggerEdge,
	uint32_t HardwareTriggerCount,
	uint32_t ByTriggerNbrOfSeqToAcquire,
	uint32_t DataFormat,
	uint32_t Option1,
	uint32_t Option2,
	uint32_t Option3,
	uint32_t Option4,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MX371x__TransducerInitAndStartSequenceEx_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.TransducerSelection = MODBUS_NTOHL(TransducerSelection);
	MODBUS_DBG("TransducerSelection=%u\n",(uint32_t)MODBUS_NTOHL(params.TransducerSelection));
	params.NbrOfChannel = MODBUS_NTOHL(NbrOfChannel);
	MODBUS_DBG("NbrOfChannel=%u\n",(uint32_t)MODBUS_NTOHL(params.NbrOfChannel));
	{
		int i;
		for(i=0;i<8;i++)
		{
			params.ChannelList[i] = MODBUS_NTOHL(ChannelList[i]);
			MODBUS_DBG("ChannelList=%u\n",(uint32_t)MODBUS_NTOHL(params.ChannelList[i]));
		}
	}
	params.NbrOfSequence = MODBUS_NTOHL(NbrOfSequence);
	MODBUS_DBG("NbrOfSequence=%u\n",(uint32_t)MODBUS_NTOHL(params.NbrOfSequence));
	params.NbrMaxSequenceToTransfer = MODBUS_NTOHL(NbrMaxSequenceToTransfer);
	MODBUS_DBG("NbrMaxSequenceToTransfer=%u\n",(uint32_t)MODBUS_NTOHL(params.NbrMaxSequenceToTransfer));
	params.DelayMode = MODBUS_NTOHL(DelayMode);
	MODBUS_DBG("DelayMode=%u\n",(uint32_t)MODBUS_NTOHL(params.DelayMode));
	params.DelayTimeUnit = MODBUS_NTOHL(DelayTimeUnit);
	MODBUS_DBG("DelayTimeUnit=%u\n",(uint32_t)MODBUS_NTOHL(params.DelayTimeUnit));
	params.DelayValue = MODBUS_NTOHL(DelayValue);
	MODBUS_DBG("DelayValue=%u\n",(uint32_t)MODBUS_NTOHL(params.DelayValue));
	params.TriggerMask = MODBUS_NTOHL(TriggerMask);
	MODBUS_DBG("TriggerMask=%u\n",(uint32_t)MODBUS_NTOHL(params.TriggerMask));
	params.TriggerMode = MODBUS_NTOHL(TriggerMode);
	MODBUS_DBG("TriggerMode=%u\n",(uint32_t)MODBUS_NTOHL(params.TriggerMode));
	params.HardwareTriggerEdge = MODBUS_NTOHL(HardwareTriggerEdge);
	MODBUS_DBG("HardwareTriggerEdge=%u\n",(uint32_t)MODBUS_NTOHL(params.HardwareTriggerEdge));
	params.HardwareTriggerCount = MODBUS_NTOHL(HardwareTriggerCount);
	MODBUS_DBG("HardwareTriggerCount=%u\n",(uint32_t)MODBUS_NTOHL(params.HardwareTriggerCount));
	params.ByTriggerNbrOfSeqToAcquire = MODBUS_NTOHL(ByTriggerNbrOfSeqToAcquire);
	MODBUS_DBG("ByTriggerNbrOfSeqToAcquire=%u\n",(uint32_t)MODBUS_NTOHL(params.ByTriggerNbrOfSeqToAcquire));
	params.DataFormat = MODBUS_NTOHL(DataFormat);
	MODBUS_DBG("DataFormat=%u\n",(uint32_t)MODBUS_NTOHL(params.DataFormat));
	params.Option1 = MODBUS_NTOHL(Option1);
	MODBUS_DBG("Option1=%u\n",(uint32_t)MODBUS_NTOHL(params.Option1));
	params.Option2 = MODBUS_NTOHL(Option2);
	MODBUS_DBG("Option2=%u\n",(uint32_t)MODBUS_NTOHL(params.Option2));
	params.Option3 = MODBUS_NTOHL(Option3);
	MODBUS_DBG("Option3=%u\n",(uint32_t)MODBUS_NTOHL(params.Option3));
	params.Option4 = MODBUS_NTOHL(Option4);
	MODBUS_DBG("Option4=%u\n",(uint32_t)MODBUS_NTOHL(params.Option4));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1350,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MX371x__TransducerStopAndReleaseSequence(struct modbus * modbus,
	uint32_t Dummy,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MX371x__TransducerStopAndReleaseSequence_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.Dummy = MODBUS_NTOHL(Dummy);
	MODBUS_DBG("Dummy=%u\n",(uint32_t)MODBUS_NTOHL(params.Dummy));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 4,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MX371x__TransducerStopAndReleaseSequenceEx(struct modbus * modbus,
	uint32_t Dummy,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MX371x__TransducerStopAndReleaseSequenceEx_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.Dummy = MODBUS_NTOHL(Dummy);
	MODBUS_DBG("Dummy=%u\n",(uint32_t)MODBUS_NTOHL(params.Dummy));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1400,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__ExternalTemperatureInit(struct modbus * modbus,
	uint32_t ConnectedTempSensor,
	uint32_t ConvertMode,
	uint32_t GainSelection,
	uint32_t FrequencySelection,
	uint32_t PowerSaveMode,
	uint32_t Option01,
	uint32_t Option02,
	uint32_t Option03,
	uint32_t Option04,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__ExternalTemperatureInit_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.ConnectedTempSensor = MODBUS_NTOHL(ConnectedTempSensor);
	MODBUS_DBG("ConnectedTempSensor=%u\n",(uint32_t)MODBUS_NTOHL(params.ConnectedTempSensor));
	params.ConvertMode = MODBUS_NTOHL(ConvertMode);
	MODBUS_DBG("ConvertMode=%u\n",(uint32_t)MODBUS_NTOHL(params.ConvertMode));
	params.GainSelection = MODBUS_NTOHL(GainSelection);
	MODBUS_DBG("GainSelection=%u\n",(uint32_t)MODBUS_NTOHL(params.GainSelection));
	params.FrequencySelection = MODBUS_NTOHL(FrequencySelection);
	MODBUS_DBG("FrequencySelection=%u\n",(uint32_t)MODBUS_NTOHL(params.FrequencySelection));
	params.PowerSaveMode = MODBUS_NTOHL(PowerSaveMode);
	MODBUS_DBG("PowerSaveMode=%u\n",(uint32_t)MODBUS_NTOHL(params.PowerSaveMode));
	params.Option01 = MODBUS_NTOHL(Option01);
	MODBUS_DBG("Option01=%u\n",(uint32_t)MODBUS_NTOHL(params.Option01));
	params.Option02 = MODBUS_NTOHL(Option02);
	MODBUS_DBG("Option02=%u\n",(uint32_t)MODBUS_NTOHL(params.Option02));
	params.Option03 = MODBUS_NTOHL(Option03);
	MODBUS_DBG("Option03=%u\n",(uint32_t)MODBUS_NTOHL(params.Option03));
	params.Option04 = MODBUS_NTOHL(Option04);
	MODBUS_DBG("Option04=%u\n",(uint32_t)MODBUS_NTOHL(params.Option04));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 5,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__ExternalTemperatureInitEx(struct modbus * modbus,
	uint32_t ConnectedTempSensor,
	uint32_t ConvertMode,
	uint32_t GainSelection,
	uint32_t FrequencySelection,
	uint32_t PowerSaveMode,
	uint32_t Option01,
	uint32_t Option02,
	uint32_t Option03,
	uint32_t Option04,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__ExternalTemperatureInitEx_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.ConnectedTempSensor = MODBUS_NTOHL(ConnectedTempSensor);
	MODBUS_DBG("ConnectedTempSensor=%u\n",(uint32_t)MODBUS_NTOHL(params.ConnectedTempSensor));
	params.ConvertMode = MODBUS_NTOHL(ConvertMode);
	MODBUS_DBG("ConvertMode=%u\n",(uint32_t)MODBUS_NTOHL(params.ConvertMode));
	params.GainSelection = MODBUS_NTOHL(GainSelection);
	MODBUS_DBG("GainSelection=%u\n",(uint32_t)MODBUS_NTOHL(params.GainSelection));
	params.FrequencySelection = MODBUS_NTOHL(FrequencySelection);
	MODBUS_DBG("FrequencySelection=%u\n",(uint32_t)MODBUS_NTOHL(params.FrequencySelection));
	params.PowerSaveMode = MODBUS_NTOHL(PowerSaveMode);
	MODBUS_DBG("PowerSaveMode=%u\n",(uint32_t)MODBUS_NTOHL(params.PowerSaveMode));
	params.Option01 = MODBUS_NTOHL(Option01);
	MODBUS_DBG("Option01=%u\n",(uint32_t)MODBUS_NTOHL(params.Option01));
	params.Option02 = MODBUS_NTOHL(Option02);
	MODBUS_DBG("Option02=%u\n",(uint32_t)MODBUS_NTOHL(params.Option02));
	params.Option03 = MODBUS_NTOHL(Option03);
	MODBUS_DBG("Option03=%u\n",(uint32_t)MODBUS_NTOHL(params.Option03));
	params.Option04 = MODBUS_NTOHL(Option04);
	MODBUS_DBG("Option04=%u\n",(uint32_t)MODBUS_NTOHL(params.Option04));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1450,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__ExternalTemperatureRelease(struct modbus * modbus,
	uint32_t Dummy,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__ExternalTemperatureRelease_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.Dummy = MODBUS_NTOHL(Dummy);
	MODBUS_DBG("Dummy=%u\n",(uint32_t)MODBUS_NTOHL(params.Dummy));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 6,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__ExternalTemperatureReleaseEx(struct modbus * modbus,
	uint32_t Dummy,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__ExternalTemperatureReleaseEx_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.Dummy = MODBUS_NTOHL(Dummy);
	MODBUS_DBG("Dummy=%u\n",(uint32_t)MODBUS_NTOHL(params.Dummy));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1500,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MX371x__SetTransducerDatabaseCursor(struct modbus * modbus,
	uint32_t TransducerDatabaseCursor,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MX371x__SetTransducerDatabaseCursor_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.TransducerDatabaseCursor = MODBUS_NTOHL(TransducerDatabaseCursor);
	MODBUS_DBG("TransducerDatabaseCursor=%u\n",(uint32_t)MODBUS_NTOHL(params.TransducerDatabaseCursor));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 7,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MX371x__SetTransducerDatabaseCursorEx(struct modbus * modbus,
	uint32_t TransducerDatabaseCursor,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MX371x__SetTransducerDatabaseCursorEx_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.TransducerDatabaseCursor = MODBUS_NTOHL(TransducerDatabaseCursor);
	MODBUS_DBG("TransducerDatabaseCursor=%u\n",(uint32_t)MODBUS_NTOHL(params.TransducerDatabaseCursor));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1504,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__IncCounterInit(struct modbus * modbus,
	uint32_t ulCounterMode,
	uint32_t ulCounterOption,
	uint32_t ulOption01,
	uint32_t ulOption02,
	uint32_t ulOption03,
	uint32_t ulOption04,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__IncCounterInit_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.ulCounterMode = MODBUS_NTOHL(ulCounterMode);
	MODBUS_DBG("ulCounterMode=%u\n",(uint32_t)MODBUS_NTOHL(params.ulCounterMode));
	params.ulCounterOption = MODBUS_NTOHL(ulCounterOption);
	MODBUS_DBG("ulCounterOption=%u\n",(uint32_t)MODBUS_NTOHL(params.ulCounterOption));
	params.ulOption01 = MODBUS_NTOHL(ulOption01);
	MODBUS_DBG("ulOption01=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption01));
	params.ulOption02 = MODBUS_NTOHL(ulOption02);
	MODBUS_DBG("ulOption02=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption02));
	params.ulOption03 = MODBUS_NTOHL(ulOption03);
	MODBUS_DBG("ulOption03=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption03));
	params.ulOption04 = MODBUS_NTOHL(ulOption04);
	MODBUS_DBG("ulOption04=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption04));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1650,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__IncCounterRelease(struct modbus * modbus,
	uint32_t ulOption01,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__IncCounterRelease_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.ulOption01 = MODBUS_NTOHL(ulOption01);
	MODBUS_DBG("ulOption01=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption01));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1700,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__IncCounterClear(struct modbus * modbus,
	uint32_t ulOption01,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__IncCounterClear_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.ulOption01 = MODBUS_NTOHL(ulOption01);
	MODBUS_DBG("ulOption01=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption01));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1750,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__IncCounterWrite32BitValue(struct modbus * modbus,
	uint32_t ulCounterValue,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__IncCounterWrite32BitValue_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.ulCounterValue = MODBUS_NTOHL(ulCounterValue);
	MODBUS_DBG("ulCounterValue=%u\n",(uint32_t)MODBUS_NTOHL(params.ulCounterValue));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1800,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__IncCounterInitAndEnableCompareLogic(struct modbus * modbus,
	uint32_t ulValue,
	uint32_t ulMode,
	uint32_t ulSynchroTrigger,
	uint32_t ulOption01,
	uint32_t ulOption02,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__IncCounterInitAndEnableCompareLogic_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.ulValue = MODBUS_NTOHL(ulValue);
	MODBUS_DBG("ulValue=%u\n",(uint32_t)MODBUS_NTOHL(params.ulValue));
	params.ulMode = MODBUS_NTOHL(ulMode);
	MODBUS_DBG("ulMode=%u\n",(uint32_t)MODBUS_NTOHL(params.ulMode));
	params.ulSynchroTrigger = MODBUS_NTOHL(ulSynchroTrigger);
	MODBUS_DBG("ulSynchroTrigger=%u\n",(uint32_t)MODBUS_NTOHL(params.ulSynchroTrigger));
	params.ulOption01 = MODBUS_NTOHL(ulOption01);
	MODBUS_DBG("ulOption01=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption01));
	params.ulOption02 = MODBUS_NTOHL(ulOption02);
	MODBUS_DBG("ulOption02=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption02));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1850,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__IncCounterDisableAndReleaseCompareLogic(struct modbus * modbus,
	uint32_t ulOption01,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__IncCounterDisableAndReleaseCompareLogic_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.ulOption01 = MODBUS_NTOHL(ulOption01);
	MODBUS_DBG("ulOption01=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption01));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 1900,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__IncCounterInitAndEnableIndex(struct modbus * modbus,
	uint32_t ulReferenceAction,
	uint32_t ulIndexOperation,
	uint32_t ulAutoMode,
	uint32_t ulOption01,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__IncCounterInitAndEnableIndex_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.ulReferenceAction = MODBUS_NTOHL(ulReferenceAction);
	MODBUS_DBG("ulReferenceAction=%u\n",(uint32_t)MODBUS_NTOHL(params.ulReferenceAction));
	params.ulIndexOperation = MODBUS_NTOHL(ulIndexOperation);
	MODBUS_DBG("ulIndexOperation=%u\n",(uint32_t)MODBUS_NTOHL(params.ulIndexOperation));
	params.ulAutoMode = MODBUS_NTOHL(ulAutoMode);
	MODBUS_DBG("ulAutoMode=%u\n",(uint32_t)MODBUS_NTOHL(params.ulAutoMode));
	params.ulOption01 = MODBUS_NTOHL(ulOption01);
	MODBUS_DBG("ulOption01=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption01));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 2000,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}
int modbus_call_MSXE371x__IncCounterDisableAndReleaseIndex(struct modbus * modbus,
	uint32_t ulOption01,
	struct GetLastCommandStatus_parameters_t * CommandStatus)
{
	struct MSXE371x__IncCounterDisableAndReleaseIndex_parameters_t params;

	MODBUS_DBG("%s",__FUNCTION__);

	memset(CommandStatus,0,sizeof(struct GetLastCommandStatus_parameters_t));

	/* store parameters in structure */
	params.ulOption01 = MODBUS_NTOHL(ulOption01);
	MODBUS_DBG("ulOption01=%u\n",(uint32_t)MODBUS_NTOHL(params.ulOption01));
	
	/* call generic FC16 function */
	{
		int ret; /* return value */
		ret = modbus_send_FC16_query(modbus, 2100,0, (char*) &params, sizeof(params));
		switch(ret)
		{
			case 0: /* OK */
			case -1: /* local system error (in errno) */
			case -3: /* incorrect response from remote system */
				return ret;
			case -2: /* MODBUS exception */
			{
				if (modbus->exception != MODBUS_REMOTE_EXECUTION_ERROR ) return ret;
				/* try to get the cause */
				switch(modbus_call_GetLastCommandStatus(modbus,CommandStatus))
				{
					case 0: /*  OK - user can use CommandStatus */
						return ret;
					default: /*  We are in trouble */
						return -4;
				}
			}
			default: /* internal error */
				MODBUS_ON_INTERNAL_ERROR();
		}
	}
}


